packages:
  - "apps/*"
  - "internal/*"
  - "packages/*"

catalogMode: prefer

catalog:
  "@nestjs/cli": ^11.0.24
  "@nestjs/common": ^11.1.28
  '@nestjs/config': ^4.0.4
  "@nestjs/core": ^11.1.28
  "@nestjs/mapped-types": ^2.1.1
  "@nestjs/platform-fastify": ^11.1.28
  "@nestjs/schematics": ^11.1.0
  "@types/node": ^24.0.0
  "@vitejs/plugin-vue": ^6.0.8
  antdv-next: ^1.4.6
  dotenv: ^17.4.2
  joi: ^18.2.3
  pinia: ^4.0.2
  reflect-metadata: ^0.2.2
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plugin-vue-devtools: ^8.2.1
  vite-plus: 0.2.8
  vue: ^3.5.41
  vue-router: ^5.2.0
  vue-tsc: ^3.3.9

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.8"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.8"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.8"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.8"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.8"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.8"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.8"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.8"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.8"
  - vite-plus@0.2.8
